CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(64) NOT NULL,
  grade_level VARCHAR(32) NOT NULL,
  parent_name VARCHAR(255),
  parent_phone VARCHAR(64),
  premium_status BOOLEAN DEFAULT FALSE,
  points INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weekly_lessons (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  week_key VARCHAR(32) NOT NULL,
  mission_title VARCHAR(255) NOT NULL,
  academic_lesson VARCHAR(700) NOT NULL,
  mascot_line VARCHAR(700) NOT NULL,
  game_shell VARCHAR(255) NOT NULL,
  subject VARCHAR(64) NOT NULL,
  tier VARCHAR(32) NOT NULL,
  prompt VARCHAR(700) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  reward VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS progress_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  game_shell VARCHAR(255) NOT NULL,
  subject VARCHAR(64) NOT NULL,
  tier VARCHAR(32) NOT NULL,
  score INT DEFAULT 0,
  knowledge_leaf VARCHAR(255) NOT NULL,
  completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
